# TOML file for keyboard configuration.
#
# This is for the M-AUDIO Oxygen 8 v2, with
# the control values after factory reset (power on while
# holding + and -). I recommend velocity curve 5 rather than
# the default: see the manual.

# MIDI keyboard name: can be overridden on command line.
name = "USB Oxygen 8 v2"

# List of control messages that should be suppressed /
# ignored. My controller was sending spurious messages for a
# while, but seems to be better now.
# suppressed = []

[controls]
# Volume knob (Knob C5)
volume = 71
# Mod Wheel
modwheel = 1
# Parameter 1 (Knob C1)
param1 = 91
# Button that will stop the synthesizer immediately and exit
# when pressed (Media "stop key" -- square)
stop = 23
